apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flaskapp
  labels:
    deployment: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: flaskapp
  template:
    metadata:
      labels:
        pod: flaskapp
    spec:
      containers:
        - name: flaskapp
          image: makeapp007/cloud-ml-final-project_flaskapp:2054
          imagePullPolicy: Always
          command: ["gunicorn", "--workers=4", "--bind=0.0.0.0:8000", "app:app" ,"--timeout=30", "--log-level", "debug"]
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: redis-service
          
          volumeMounts:
            - name: mypvc
              mountPath: /cloudfinal/.vector_cache
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: mypvc
