apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  labels:
    billingType: "hourly"
    region: us-south
    zone: dal10
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 24Gi
  storageClassName: ibmc-block-silver
