DATA_ROOT='../aclImdb'
MAX_VOCAB_SIZE=25000

# Default parameters
EMBEDDING_SIZE=100
HIDDEN_DIM = 256
LR=0.01
BATCH_SIZE=64
LAYER_DEPTH=2
CNN_N_FILTERS=100
SAVE_MODEL=1
OUTPUT_FILE='../models'
GRAD_CLIP=2
EPOCH=100
GET_LOSS=1
MAX_TRAIN_NUM=None
DROPOUT=0.5
OUTPUT_DIM=1
PRETRAIN=False
OPTIM='Adam'
use_cuda=True
BIDIRECTIONAL=True
