apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: celery-worker
  labels:
    deployment: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: celery-worker
  template:
    metadata:
      labels:
        pod: celery-worker
    spec:
      containers:
        - name: celery-worker
          image: makeapp007/cloud-ml-final-project_flaskapp:2345
          imagePullPolicy: Always
          command: ['celery', 'worker', '-A', 'train.train.celery', '--loglevel=info']
          env:
            - name: REDIS_HOST
              value: redis-service
